### ISSUE TITLE
update links

### ISSUE THREAD

**Issue by Arhell** [collective/collective.qwebirc#3]

**Comment by ale-rt** [comment]
Please do not.

I appreciate your effort in contributing but It would be nice if you could stop making this kind of PR in packages that do not receive an update since so many years.

First of all people might think they are still supported, which is hardly the case.
Second many changes you are doing are to dead links or fake ones.
Third as an organization keeper I spend my time having a look at this PRs checking that something nasty does not happen.

I welcome you to provide your expertise to more recent packages, fixing bug and documentation. There are plenty of packages that might benefit from your work.

I hope you see my point!
